config/routes.rb
Rails.application.routes.draw do
  resources :attends
  devise_for :users

  root 'welcome#index'
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
end

app/models/attend.rb
class Attend < ActiveRecord::Base
  belongs_to :user
  def self.current_date_attendances
    where(in_date: Date.today)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :attends
  def full_name
    first_name.present? && last_name.present? ? first_name + ' ' + last_name : (first_name.present? ? first_name : last_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:email, :password, :password_confirmation, :first_name, :last_name)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit!#(:email, :password, :password_confirmation, :current_password, :first_name, :last_name)
    end
    devise_parameter_sanitizer.for(:sign_in) do |u|
      u.permit(:email, :password)
    end
  end

end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController
  before_action :set_attend, only: [:show, :edit, :update, :destroy]

  # GET /attends
  # GET /attends.json
  def index
    @attends = Attend.all
  end

  # GET /attends/1
  # GET /attends/1.json
  def show
  end

  # GET /attends/new
  def new
    @attend = Attend.new
  end

  # GET /attends/1/edit
  def edit
  end

  # POST /attends
  # POST /attends.json
  def create
    @attend = current_user.attends.build(in_date:Date.today ,in_time:Time.now)
    respond_to do |format|
      if @attend.save
        format.html { redirect_to root_path, notice: 'Attend was successfully created.' }
        format.json { render :show, status: :created, location: @attend }
      else
        format.html { render :new }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attends/1
  # PATCH/PUT /attends/1.json
  def update
    respond_to do |format|
      attend = Attend.find_by_id(params[:id])
      duration = Time.now - attend.in_time
      if attend.update(out_time:Time.now, duration: duration)
        format.html { redirect_to root_path, notice: 'Attend was successfully updated.' }
        format.json { render :show, status: :ok, location: @attend }
      else
        format.html { render :edit }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attends/1
  # DELETE /attends/1.json
  def destroy
    @attend.destroy
    respond_to do |format|
      format.html { redirect_to attends_url, notice: 'Attend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attend
      @attend = Attend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attend_params
      params.require(:attend).permit(:in_date, :in_time, :out_time, :duration, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @attendances = current_user.attends.current_date_attendances
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def in_out_select(attendances)
    if attendances.present?
        if attendances.last.out_time.present?
          link_to 'In', attends_path, method: :post, class:'btn btn-success'
        else
          link_to 'Out', attend_path(id: attendances.last.id), method: :put, class:'btn btn-danger'
        end
    else
      link_to 'In', attends_path, method: :post, class:'btn btn-success'
    end
  end
end

app/helpers/attends_helper.rb
module AttendsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attends/_form.html.erb
<%= form_for(@attend) do |f| %>
  <% if @attend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attend.errors.count, "error") %> prohibited this attend from being saved:</h2>

      <ul>
      <% @attend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :in_date %><br>
    <%= f.date_select :in_date %>
  </div>
  <div class="field">
    <%= f.label :in_time %><br>
    <%= f.datetime_select :in_time %>
  </div>
  <div class="field">
    <%= f.label :out_time %><br>
    <%= f.datetime_select :out_time %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attends/edit.html.erb
<h1>Editing Attend</h1>

<%= render 'form' %>

<%= link_to 'Show', @attend %> |
<%= link_to 'Back', attends_path %>

app/views/attends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attends</h1>

<table>
  <thead>
    <tr>
      <th>In date</th>
      <th>In time</th>
      <th>Out time</th>
      <th>Duration</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attends.each do |attend| %>
      <tr>
        <td><%= attend.in_date %></td>
        <td><%= attend.in_time %></td>
        <td><%= attend.out_time %></td>
        <td><%= attend.duration %></td>
        <td><%= attend.user_id %></td>
        <td><%= link_to 'Show', attend %></td>
        <td><%= link_to 'Edit', edit_attend_path(attend) %></td>
        <td><%= link_to 'Destroy', attend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attend', new_attend_path %>

app/views/attends/new.html.erb
<h1>New Attend</h1>

<%= render 'form' %>

<%= link_to 'Back', attends_path %>

app/views/attends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>In date:</strong>
  <%= @attend.in_date %>
</p>

<p>
  <strong>In time:</strong>
  <%= @attend.in_time %>
</p>

<p>
  <strong>Out time:</strong>
  <%= @attend.out_time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @attend.duration %>
</p>

<p>
  <strong>User:</strong>
  <%= @attend.user_id %>
</p>

<%= link_to 'Edit', edit_attend_path(@attend) %> |
<%= link_to 'Back', attends_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Attendance</title>
  <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/header' %>
    <div class="container">
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_footer.html.erb
<footer></footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
        <% else %>
            <li>
              <%= link_to('Login', new_user_session_path)  %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-6">
    <%= in_out_select(@attendances).html_safe %>
  </div>
  <div class="col-md-6">
    <h3><%= current_user.full_name %></h3>
    <h4><%= current_user.email %></h4>
  </div>
</div>
<div class="row">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Attendance of <%= current_user.full_name %></h3>
    </div>
    <div class="panel-body">
      <table class="table table-responsive">
        <thead>
        <tr>
          <th>Date</th>
          <th>In</th>
          <th>Out</th>
          <th>Duration</th>
        </tr>
        </thead>
        <tbody>
        <% @attendances.each do |attendance| %>
            <tr>
              <td><%= attendance.in_date %></td>
              <td><%= attendance.in_time %></td>
              <td><%= attendance.out_time %></td>
              <td><%= attendance.duration %></td>
            </tr>
        <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>